# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

# Implements wordpress, db and wp-cli Docker Compose services that are exposed
# to any project using this tool by including this file in its COMPOSE_FILE
# path.

version: "3.6"

# Environment settings that are common to the wp and wp-cli services.
x-wp-env: &wp-env
  WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}_db
  WORDPRESS_DB_NAME: wordpress
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: '' # prevent fallback to 'example_password'

services:

  wordpress:

    # This image is explicitly named so that the proxy server implemented by our
    # proxy tool (https://github.com/varilink/tools-proxy) can proxy requests to
    # it by host name.
    image: wordpress:${WORDPRESS_TAG:-latest}

    container_name: ${COMPOSE_PROJECT_NAME}

    depends_on:
      - db
      - proxy

    environment:
      <<: *wp-env
      # Disable automatic updates for WordPress in our desktop environment.
      WORDPRESS_CONFIG_EXTRA: |-
        define('WP_AUTO_UPDATE_CORE', false);
      WORDPRESS_DEBUG: 1

    volumes:
      - wordpress:/var/www/html

  db:

    # This image is explicitly named so that the wordpress service above can
    # connect to its database by host name.
    image: mariadb:${MARIADB_TAG:-latest}

    container_name: ${COMPOSE_PROJECT_NAME}_db

    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  wp-cli:

    build: ./tools/wordpress/wp-cli

    environment:
      COMPOSE_PROJECT_NAME:
      <<: *wp-env

    volumes:
      - wordpress:/var/www/html
      - ./wxr:/wxr

  pma:

    image: phpmyadmin

    container_name: ${COMPOSE_PROJECT_NAME}_pma

    environment:
      PMA_HOST: ${COMPOSE_PROJECT_NAME}_db
      PMA_USER: root
      PMA_PASWORD: ''

volumes:
  wordpress:
