# ------------------------------------------------------------------------------
# docker-compose.yml
# ------------------------------------------------------------------------------

# Implements wordpress, db and wp-cli Docker Compose services that are exposed
# to any project using this tool by including this file in its COMPOSE_FILE
# path.

version: "3.6"

services:

  wordpress:

    # This image is explicitly named so that the proxy server implemented by our
    # proxy tool (https://github.com/varilink/tools-proxy) can proxy requests to
    # it by host name.
    image: wordpress:${WORDPRESS_TAG}

    container_name: ${COMPOSE_PROJECT_NAME}

    depends_on:
      - db
      - proxy

    environment:
      WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}_db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '' # prevent fallback to 'example_password'
      WORDPRESS_DEBUG: 1

    volumes:
      - wordpress:/var/www/html

  db:

    # This image is explicitly named so that the wordpress service above can
    # connect to its database by host name.
    image: mariadb:${MARIADB_TAG}

    container_name: ${COMPOSE_PROJECT_NAME}_db

    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  wp-cli:

    build: ./tools/wordpress/wp-cli

    environment:
      COMPOSE_PROJECT_NAME:
      WORDPRESS_DB_HOST: ${COMPOSE_PROJECT_NAME}_db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: '' # prevent fallback to 'example_password'

    volumes:
      - wordpress:/var/www/html
      - ./posts:/posts

volumes:
  wordpress:
